---
- hosts: '{{ hosts }}'
  user: '{{ project_name }}'
  vars_files:
    - vars.yml
  gather_facts: false

  handlers:
    - include: handlers.yml

  tasks:
  - name: pull code from github
    git: repo={{ project_repo_url }} dest={{ project_repo_path }} update=yes
         force=yes

  - name: create a virtualenv with python2
    command: virtualenv -p python2.7 {{ project_venv }}
    args:
      creates: '{{ project_venv }}'

  - name: install numpy, scipy and other stuff
    pip: name={{ item }} state=latest virtualenv={{ project_venv }}
    with_items:
      - numpy
      - scipy
      - python-dateutil
      - pytz
      - cycler
      - tornado
      - pyparsing
      - pyhull
      - matplotlib

  - name: install project python packages
    pip: requirements='{{ project_repo_path }}/requirements.txt' virtualenv={{ project_venv }}
         virtualenv_site_packages=yes

- hosts: '{{ hosts }}'
  user: '{{ admin_user }}'
  vars_files:
    - vars.yml
  gather_facts: false
  sudo: yes

  handlers:
    - include: handlers.yml

  tasks:
  - name: copy the gunicorn start script
    template: src=conf/gunicorn_conf.j2 dest='{{ project_venv }}/bin/gunicorn_start'
              owner={{ project_name }} group=webapps mode=0755

  - name: copy the supervisor config file
    template: src=conf/supervisor.j2 dest='/etc/supervisor/conf.d/{{ project_name }}.conf'

  - name: restart supervisor process
    supervisorctl: name={{ project_name }}_gunicorn state=restarted

  - name: write nginx config
    template: src=conf/nginx.conf.j2 dest=/etc/nginx/nginx.conf
                owner=root group=root mode=0644
    notify: reload nginx

  - name: configure nginx site
    template: src=conf/nginx_site.j2
              dest={{ nginx_sites_enabled }}/{{ project_name }}.conf
              owner=root group=root mode=0755
    notify: reload nginx
